# Generated by Django 3.1.1 on 2020-09-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finzlist', '0003_bookmark_votes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.ManyToManyField(to='finzlist.Bookmark')),
            ],
        ),
    ]
