# Generated by Django 3.1.1 on 2020-09-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finzlist', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='site',
            field=models.ManyToManyField(to='finzlist.Bookmark'),
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_name',
        ),
        migrations.AddField(
            model_name='category',
            name='category_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
