# Generated by Django 3.1.1 on 2020-09-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finzlist', '0005_auto_20200925_0524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='site',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='category_name',
            field=models.ManyToManyField(to='finzlist.Category'),
        ),
    ]
